# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bc280400dcaac712c091b1870797b304c12b3e23da06b2be6a37f85720f3badbfb8af0e90bfa4e2ef2d4434b7506ddfdaffa2bde89bd9118f75a096e8ed41c8

test:
  secret_key_base: 9a67f32886e814e094cacf0a73e8517d7476345ebb4ec196d879ea0c4baff02b46c3314e04225e7ab9b976420862bf7886eb2b20890f2a10642d771fb2969a96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
